'use strict';

/**
 * Generate a self-contained HTML report from analysis data.
 */
function generateHtmlReport(data) {
  const { analysis, lagEvents, slowIOEvents, config, timestamp } = data;
  const reportTime = new Date(timestamp || Date.now()).toISOString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>loop-detective report — ${reportTime}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0d1117;color:#c9d1d9;line-height:1.6;padding:24px;max-width:1100px;margin:0 auto}
h1{color:#58a6ff;font-size:1.6em;margin-bottom:4px}
h2{color:#c9d1d9;font-size:1.2em;margin:28px 0 12px;padding-bottom:6px;border-bottom:1px solid #21262d}
.meta{color:#8b949e;font-size:.85em;margin-bottom:24px}
.card{background:#161b22;border:1px solid #21262d;border-radius:8px;padding:16px;margin-bottom:16px}
.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:20px}
.stat{background:#161b22;border:1px solid #21262d;border-radius:8px;padding:16px;text-align:center}
.stat-value{font-size:1.8em;font-weight:700;color:#58a6ff}
.stat-label{font-size:.8em;color:#8b949e;margin-top:2px}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.75em;font-weight:600;margin-right:6px}
.badge-high{background:#da3633;color:#fff}
.badge-medium{background:#d29922;color:#000}
.badge-low{background:#238636;color:#fff}
.pattern{margin-bottom:14px}
.pattern-msg{margin:4px 0 2px 0}
.pattern-loc{color:#8b949e;font-size:.85em}
.pattern-sug{color:#58a6ff;font-size:.9em}
table{width:100%;border-collapse:collapse;font-size:.9em}
th{text-align:left;padding:8px 10px;border-bottom:2px solid #21262d;color:#8b949e;font-weight:600}
td{padding:8px 10px;border-bottom:1px solid #21262d}
tr:hover td{background:#1c2128}
.bar-container{width:100%;background:#21262d;border-radius:3px;height:18px;position:relative}
.bar-fill{height:100%;border-radius:3px;min-width:2px}
.bar-red{background:#da3633}
.bar-yellow{background:#d29922}
.bar-green{background:#238636}
.bar-label{position:absolute;right:6px;top:0;line-height:18px;font-size:.75em;color:#c9d1d9}
.stack{font-family:'SF Mono',Consolas,monospace;font-size:.82em;background:#0d1117;border:1px solid #21262d;border-radius:6px;padding:10px;margin:6px 0 12px;overflow-x:auto}
.stack-line{color:#8b949e;padding:1px 0}
.stack-target{color:#d29922;font-weight:600}
.io-type{font-size:1.1em;margin:10px 0 6px}
.lag-timeline{display:flex;flex-wrap:wrap;gap:4px;margin:8px 0}
.lag-dot{width:10px;height:10px;border-radius:50%;cursor:pointer;position:relative}
.lag-dot:hover::after{content:attr(data-tip);position:absolute;bottom:14px;left:50%;transform:translateX(-50%);background:#161b22;border:1px solid #21262d;padding:4px 8px;border-radius:4px;font-size:.75em;white-space:nowrap;z-index:1;color:#c9d1d9}
.collapsible{cursor:pointer;user-select:none}
.collapsible::before{content:'▸ ';color:#8b949e}
.collapsible.open::before{content:'▾ '}
.collapse-content{display:none;margin-top:6px}
.collapse-content.show{display:block}
.empty{color:#238636;padding:12px 0}
footer{margin-top:32px;padding-top:12px;border-top:1px solid #21262d;color:#8b949e;font-size:.8em;text-align:center}
</style>
</head>
<body>
<h1>🔍 loop-detective report</h1>
<div class="meta">Generated ${reportTime} · Duration ${analysis.summary.totalDurationMs}ms · ${analysis.summary.samplesCount} samples</div>

${renderSummary(analysis.summary, lagEvents, slowIOEvents)}
${renderPatterns(analysis.blockingPatterns)}
${renderHeavyFunctions(analysis.heavyFunctions)}
${renderCallStacks(analysis.callStacks)}
${renderSlowIO(slowIOEvents)}
${renderLagEvents(lagEvents)}

<footer>Generated by <a href="https://github.com/iwtxokhtd83/node-loop-detective" style="color:#58a6ff">node-loop-detective</a></footer>

<script>
document.querySelectorAll('.collapsible').forEach(el=>{
  el.addEventListener('click',()=>{
    el.classList.toggle('open');
    el.nextElementSibling.classList.toggle('show');
  });
});
</script>
</body>
</html>`;
}

function renderSummary(summary, lagEvents, slowIOEvents) {
  return `<div class="summary-grid">
  <div class="stat"><div class="stat-value">${summary.totalDurationMs}ms</div><div class="stat-label">Duration</div></div>
  <div class="stat"><div class="stat-value">${summary.samplesCount}</div><div class="stat-label">CPU Samples</div></div>
  <div class="stat"><div class="stat-value">${summary.heavyFunctionCount}</div><div class="stat-label">Hot Functions</div></div>
  <div class="stat"><div class="stat-value">${lagEvents.length}</div><div class="stat-label">Lag Events</div></div>
  <div class="stat"><div class="stat-value">${slowIOEvents.length}</div><div class="stat-label">Slow I/O Ops</div></div>
</div>`;
}

function renderPatterns(patterns) {
  const items = patterns.map(p => {
    const cls = p.severity === 'high' ? 'badge-high' : p.severity === 'medium' ? 'badge-medium' : 'badge-low';
    const loc = p.location ? `<div class="pattern-loc">at ${esc(p.location)}</div>` : '';
    return `<div class="pattern">
  <span class="badge ${cls}">${p.severity.toUpperCase()}</span> <strong>${esc(p.type)}</strong>
  <div class="pattern-msg">${esc(p.message)}</div>
  ${loc}
  <div class="pattern-sug">→ ${esc(p.suggestion)}</div>
</div>`;
  }).join('');
  return `<h2>Diagnosis</h2><div class="card">${items}</div>`;
}

function renderHeavyFunctions(fns) {
  if (!fns.length) return '';
  const rows = fns.map((f, i) => {
    const cls = f.percentage > 50 ? 'bar-red' : f.percentage > 20 ? 'bar-yellow' : 'bar-green';
    return `<tr>
  <td>${i + 1}</td>
  <td>${esc(f.functionName)}</td>
  <td><div class="bar-container"><div class="bar-fill ${cls}" style="width:${Math.max(f.percentage, 1)}%"></div><div class="bar-label">${f.percentage}%</div></div></td>
  <td>${f.selfTimeMs}ms</td>
  <td style="color:#8b949e;font-size:.85em">${esc(f.url)}:${f.lineNumber}</td>
</tr>`;
  }).join('');
  return `<h2>Top CPU-Heavy Functions</h2>
<div class="card"><table><thead><tr><th>#</th><th>Function</th><th>CPU</th><th>Self Time</th><th>Location</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}

function renderCallStacks(stacks) {
  if (!stacks.length) return '';
  const items = stacks.map(s => {
    const lines = s.stack.map(f => {
      const cls = f.functionName === s.target ? 'stack-target' : 'stack-line';
      const arrow = f.functionName === s.target ? '→' : '│';
      return `<div class="${cls}">${arrow} ${esc(f.functionName)} ${esc(f.url)}:${f.lineNumber}</div>`;
    }).join('');
    return `<div class="collapsible"><strong>${esc(s.target)}</strong> (${s.selfTimeMs}ms)</div>
<div class="collapse-content"><div class="stack">${lines}</div></div>`;
  }).join('');
  return `<h2>Call Stacks</h2><div class="card">${items}</div>`;
}

function renderSlowIO(events) {
  if (!events.length) return `<h2>Slow Async I/O</h2><div class="card"><div class="empty">✔ No slow I/O operations detected</div></div>`;

  const byType = {};
  for (const op of events) {
    if (!byType[op.type]) byType[op.type] = [];
    byType[op.type].push(op);
  }

  let html = '';
  for (const [type, ops] of Object.entries(byType)) {
    const icon = type === 'http' ? '🌐' : type === 'fetch' ? '🌐' : type === 'dns' ? '🔍' : '🔌';
    const maxDur = Math.max(...ops.map(o => o.duration));
    const avgDur = Math.round(ops.reduce((s, o) => s + o.duration, 0) / ops.length);

    const byTarget = {};
    for (const op of ops) {
      const key = (op.type === 'http' || op.type === 'fetch') ? op.method + ' ' + op.target : op.target;
      if (!byTarget[key]) byTarget[key] = { count: 0, total: 0, max: 0, errors: 0, stack: op.stack };
      byTarget[key].count++;
      byTarget[key].total += op.duration;
      byTarget[key].max = Math.max(byTarget[key].max, op.duration);
      if (op.error) byTarget[key].errors++;
    }

    const sorted = Object.entries(byTarget).sort((a, b) => b[1].total - a[1].total);
    const rows = sorted.map(([target, s]) => {
      const errBadge = s.errors > 0 ? ` <span class="badge badge-high">${s.errors} errors</span>` : '';
      const stackHtml = s.stack && s.stack.length > 0
        ? '<div class="stack">' + s.stack.slice(0, 3).map(l => '<div class="stack-line">' + esc(l) + '</div>').join('') + '</div>'
        : '';
      return `<tr><td>${esc(target)}${errBadge}</td><td>${s.count}</td><td>${s.total}ms</td><td>${Math.round(s.total / s.count)}ms</td><td>${s.max}ms</td></tr>
${stackHtml ? '<tr><td colspan="5">' + stackHtml + '</td></tr>' : ''}`;
    }).join('');

    html += `<div class="io-type">${icon} <strong>${type.toUpperCase()}</strong> — ${ops.length} ops, avg ${avgDur}ms, max ${maxDur}ms</div>
<table><thead><tr><th>Target</th><th>Calls</th><th>Total</th><th>Avg</th><th>Max</th></tr></thead><tbody>${rows}</tbody></table>`;
  }

  return `<h2>Slow Async I/O</h2><div class="card">${html}</div>`;
}

function renderLagEvents(events) {
  if (!events.length) return `<h2>Event Loop Lag</h2><div class="card"><div class="empty">✔ No event loop lag detected above threshold</div></div>`;

  const maxLag = Math.max(...events.map(e => e.lag));
  const avgLag = Math.round(events.reduce((s, e) => s + e.lag, 0) / events.length);

  const dots = events.map(e => {
    const pct = Math.min(e.lag / Math.max(maxLag, 1), 1);
    const color = e.lag > 500 ? '#da3633' : e.lag > 200 ? '#d29922' : '#58a6ff';
    const size = 8 + Math.round(pct * 12);
    const tip = e.lag + 'ms at ' + new Date(e.timestamp).toISOString().slice(11, 23);
    return `<div class="lag-dot" style="width:${size}px;height:${size}px;background:${color}" data-tip="${tip}"></div>`;
  }).join('');

  // Aggregate by location
  const locMap = {};
  for (const e of events) {
    if (e.stack && e.stack.length > 0) {
      const top = e.stack[0];
      const key = top.fn + ' ' + top.file + ':' + top.line;
      if (!locMap[key]) locMap[key] = { count: 0, total: 0, max: 0, frame: top };
      locMap[key].count++;
      locMap[key].total += e.lag;
      locMap[key].max = Math.max(locMap[key].max, e.lag);
    }
  }
  const locRows = Object.values(locMap).sort((a, b) => b.total - a.total).slice(0, 10).map(l =>
    `<tr><td>${esc(l.frame.fn)}</td><td style="color:#8b949e">${esc(l.frame.file)}:${l.frame.line}</td><td>${l.count}</td><td>${l.total}ms</td><td>${l.max}ms</td></tr>`
  ).join('');

  const locTable = Object.keys(locMap).length > 0
    ? `<table><thead><tr><th>Function</th><th>Location</th><th>Events</th><th>Total</th><th>Max</th></tr></thead><tbody>${locRows}</tbody></table>`
    : '';

  return `<h2>Event Loop Lag</h2><div class="card">
<p>${events.length} events · avg ${avgLag}ms · max ${maxLag}ms</p>
<div class="lag-timeline">${dots}</div>
${locTable}
</div>`;
}

function esc(s) {
  if (typeof s !== 'string') return String(s);
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

module.exports = { generateHtmlReport };
